version: '3.8'

services:
  # PostgreSQL for credit system
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: syntropy
      POSTGRES_USER: syntropy
      POSTGRES_PASSWORD: syntropy_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./configs/defaults/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - syntropy-net

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - syntropy-net

  # MinIO for object storage (S3-compatible)
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: syntropy
      MINIO_ROOT_PASSWORD: syntropy_dev
    volumes:
      - minio_data:/data
    networks:
      - syntropy-net

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./tools/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - syntropy-net

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: syntropy_dev
    volumes:
      - grafana_data:/var/lib/grafana
      - ./tools/monitoring/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - syntropy-net

  # Jaeger for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    networks:
      - syntropy-net

volumes:
  postgres_data:
  redis_data:
  minio_data:
  prometheus_data:
  grafana_data:

networks:
  syntropy-net:
    driver: bridge
